version: '2'
services:
  elk:
    build: './conf'
    image: sebp/elk:latest
    ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
        - "5000:5000"
        - "3332:3332"
    container_name: elk_http
